# Generated by Django 5.2.3 on 2025-06-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['pk'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
