# Generated by Django 5.2.3 on 2025-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_course_options_alter_lesson_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='education.student'),
        ),
        migrations.DeleteModel(
            name='StudentsGroup',
        ),
    ]
