# Generated by Django 5.2.3 on 2025-06-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
