# Generated by Django 5.2.3 on 2025-07-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_childmodel_parentmodel_grandchildmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='grandchildmodel',
            name='child',
        ),
        migrations.DeleteModel(
            name='ParentModel',
        ),
        migrations.DeleteModel(
            name='ChildModel',
        ),
        migrations.DeleteModel(
            name='GrandChildModel',
        ),
    ]
