# Generated by Django 5.2.3 on 2025-07-06 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_childmodel_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonfiles',
            options={'ordering': ['pk'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.teacher'),
        ),
    ]
