# Generated by Django 5.2.3 on 2025-07-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_alter_lessonfiles_options_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='lessons', to='education.course', verbose_name='Курс'),
        ),
    ]
